# Monitor service
monitor:
  build: .
  command: nodemon --exec "npm run monitor"
  links:
    - rabbitmq
  volumes:
    - .:/usr/src/app

# Needs service
needs:
  build: .
  command: nodemon --exec "npm run needs"
  links:
    - rabbitmq
  volumes:
    - .:/usr/src/app

# Location Solution service
location_solution:
  build: .
  command: nodemon --exec "npm run location_solution"
  links:
    - rabbitmq
  volumes:
    - .:/usr/src/app

# Brand Solution service
brand_solution:
  build: .
  command: nodemon --exec "npm run brand_solution"
  links:
    - rabbitmq
  volumes:
    - .:/usr/src/app


# Brand Solution service
solution_picker:
  build: .
  command: nodemon --exec "npm run solution_picker"
  links:
    - rabbitmq
  volumes:
    - .:/usr/src/app

# RabbitMQ with management console exposed
rabbitmq:
  image: rabbitmq:management
  ports:
    - "15672:15672"
